### ISSUE TITLE
Jetty is Up but WebApp is not accessible

### ISSUE THREAD

**Issue by SteveFeldman** [JH3P/Smoker-Data-WebApp#2]
I ended up using the SmokerDataApplication.jar in the root folder. However, after Jetty is up and running, I am not able to access the server via http://0.0.0.0:8080. I've tried /webapp as well as /index.html based on what's in src. 

The server is up...I'm just getting a 404. I bet there is something trivial that I'm missing...

**Comment by JH3P** [comment]
Hey Steve, i should have specified that in the readme, you should be able
to see it at http://localhost:8080, my apologies.

**Comment by SteveFeldman** [comment]
I tried but it's not accessible. Something must be up with the Jar.

**Comment by JH3P** [comment]
Hey Steve, thats a bit embarassing, I'll fix it up as soon as i get home.
Sorry for the inconvenience.

**Comment by SteveFeldman** [comment]
After the rebuild, I'm still having issues. I tried http://localhost:8080 as you mentioned. For debug purposes, I did a quick curl. See output below:

$ curl http://localhost:8080
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /. Reason:
<pre>    Not Found</pre></p><hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.3.z-SNAPSHOT</a><hr/>

</body>
</html>

**Comment by SteveFeldman** [comment]
Here's the terminal output of the java -jar command:

$ java -jar SmokerDataApplication.jar 
2016-01-03 19:59:20.013:INFO::main: Logging initialized @123ms
2016-01-03 19:59:20.098:INFO:oejs.Server:main: jetty-9.3.z-SNAPSHOT
2016-01-03 19:59:20.177:INFO:oejw.StandardDescriptorProcessor:main: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
2016-01-03 19:59:20.194:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@2eee9593{/,file:///Users/stevefeldman/Projects/candidates/Smoker-Data-WebApp/target/src/main/webapp,AVAILABLE}
2016-01-03 19:59:20.210:INFO:oejs.ServerConnector:main: Started ServerConnector@66d33a{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2016-01-03 19:59:20.211:INFO:oejs.Server:main: Started @323ms

**Comment by SteveFeldman** [comment]
You may want to take a look at this project: https://github.com/jetty-project/embedded-jetty-jsp

**Comment by JH3P** [comment]
Hey Steve, i know exactly whats going on, i unfortunately placed the
webapps folder in the wrong path, and it wasnt getting packaged in the
jar. Unfortunately I had to step out and will fix and commit as soon as I
get home. Thank you.
-Jee

**Comment by SteveFeldman** [comment]
Sounds good...I will grab the update in the morning then...

**Comment by JH3P** [comment]
Steve, please run the Jar file inside of the target folder. Thanks again.

**Comment by SteveFeldman** [comment]
You can close the issue...everything works now.
